github: [drazzardaq]
custom:
  # - https://wise.com/pay/me/dragoljubr2
  # - "Payoneer USD Community Federal Savings Bank, Routing: 026073150, Account: 8114759185, Name: Dragoljub Randjelovic"
  # - "Payoneer GBP: Bank: Barclays, Sort code: 231486, Account: 00714309, Name: Dragoljub Randjelovic"
  # - "Payoneer CAD: Bank: Citibank NA Canadian Branch, Institution: 0328, Transit: 20012, Account: 3001329115, Name: Dragoljub Randjelovic"
  # - "Payoneer AED: Bank: Standard Chartered, SWIFT: SCBLAEADXXX, IBAN: AE800446420010001036148, Name: Dragoljub Randjelovic"
  # - "Payoneer JPY: Bank: MUFG Bank, Ltd., Code: 0005, Branch: 869, Account: 2540124, Name: ﾍﾟｲｵﾆｱ ｼﾞﾌﾟﾚﾐｱﾑ(ｶ"

