// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fledvmhqwrwnidhmtwbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsZWR2bWhxd3J3bmlkaG10d2JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMzUwNzMsImV4cCI6MjA2NTgxMTA3M30.O2ZEs7OAnVQNDOKShlFKBy9b7FQg-9bX_BvAAh2yzLU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);